#!/usr/bin/env python3
"""Assemble the swing report as a single self-contained HTML file."""
import base64, json
from pathlib import Path

ROOT = Path(__file__).parent
d = json.loads((ROOT / "picks.json").read_text())
charts = ROOT / "out" / "charts"

def img(name):
    p = charts / name
    if not p.exists():
        return ""
    b = base64.b64encode(p.read_bytes()).decode()
    return f'<img src="data:image/png;base64,{b}" alt="{name}">'

css = """
body{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:980px;margin:24px auto;padding:0 16px;color:#1a202c;background:#fafafa}
h1{font-size:26px;margin-bottom:2px} h2{margin-top:36px;border-bottom:2px solid #e2e8f0;padding-bottom:6px}
.meta{color:#64748b;font-size:14px;margin-bottom:18px}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:18px 20px;margin:16px 0;box-shadow:0 1px 3px rgba(0,0,0,.05)}
.card img{width:100%;border-radius:8px;margin-top:10px;border:1px solid #eee}
.tick{font-size:20px;font-weight:700} .setup{color:#2563eb;font-weight:600}
.conv-High{color:#16a34a;font-weight:700}.conv-Medium{color:#d97706;font-weight:700}.conv-Medium-high{color:#65a30d;font-weight:700}
table.lv{border-collapse:collapse;margin:8px 0;width:100%;font-size:14px}
table.lv td,table.lv th{border:1px solid #e2e8f0;padding:6px 10px;text-align:left}
table.lv th{background:#f1f5f9}
.watch{background:#fffbeb;border-color:#fcd34d}.veto{background:#fef2f2;border-color:#fca5a5}
.disc{font-size:12px;color:#94a3b8;margin-top:30px;border-top:1px solid #e2e8f0;padding-top:10px}
.badge{display:inline-block;background:#eef2ff;color:#4338ca;border-radius:6px;padding:2px 8px;font-size:12px;margin-left:8px}
"""

h = [f"<!doctype html><html><head><meta charset='utf-8'><title>Swing Report {d['run_date']}</title><style>{css}</style></head><body>"]
h.append(f"<h1>Swing Report <span class='badge'>{d['run_date']}</span></h1>")
h.append(f"<div class='meta'>Data through {d['data_through']} · {d['universe']}<br>Funnel: {d['funnel']}</div>")

h.append(f"<h2>Top picks ({len(d['picks'])})</h2>")
for p in d["picks"]:
    conv = p["conviction"].replace(" ", "-")
    h.append("<div class='card'>")
    h.append(f"<span class='tick'>{p['ticker']}</span> — {p['name']} &nbsp; <span class='setup'>{p['setup']}</span> &nbsp; <span class='conv-{conv}'>{p['conviction']} conviction</span>")
    h.append(f"<table class='lv'><tr><th>Entry zone</th><th>Stop (below structure)</th><th>Target 1</th><th>Target 2</th><th>R:R</th><th>Size ($1.5–2k)</th></tr>")
    h.append(f"<tr><td><b>{p['entry']}</b></td><td>{p['stop']}</td><td>{p['target1']}</td><td>{p['target2']}</td><td><b>{p['rr']}</b></td><td>{p['shares']}</td></tr></table>")
    h.append(f"<p><b>Chart:</b> {p['thesis']}</p>")
    h.append(f"<p><b>Fundamental check:</b> {p['fundamental']}</p>")
    h.append(img(p["chart"]))
    h.append("</div>")

h.append("<h2>Watchlist — triggers not yet met</h2>")
for w in d["watch"]:
    h.append(f"<div class='card watch'><span class='tick'>{w['ticker']}</span><p>{w['note']}</p>{img(w.get('chart','')) if w.get('chart') else ''}</div>")

h.append("<h2>Vetoed by AI review (screener liked them — I didn't)</h2>")
for v in d["vetoed"]:
    h.append(f"<div class='card veto'><b>{v['ticker']}</b> — {v['reason']}</div>")

h.append("<div class='disc'>Generated by your swing agent from your strategy profile v1 (reversal + strong-breakout, daily timeframe, stop below structure, min 2:1 R:R, fundamentals as veto). Educational decision support — not financial advice; final decisions are yours. Prices from Yahoo Finance EOD via your swing-data repo.</div>")
h.append("</body></html>")
(ROOT / "out" / f"swing-report-{d['run_date']}.html").write_text("\n".join(h))
print("report written")
